#########################################
# Build stage
#########################################

#########################################
# Distribution stage
#########################################
FROM alpine:latest AS slim

# Repository location
ARG REPOSITORY=github.com/sigreen-nokia

# Artifact name
ARG ARTIFACT=lexx

# User
ARG USER=lexx
ARG UID=1000

# Create non-root user
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --no-create-home \
    --uid "$UID" \
    "$USER"

# Install deps
RUN apk add --no-cache bash gcompat

# Install binary
COPY --from=builder /go/src/$REPOSITORY/$ARTIFACT/release/$ARTIFACT /usr/local/bin/$ARTIFACT

VOLUME [ "/scripts" ]

EXPOSE 8080

USER $USER

CMD [ "lexx" ]

#########################################
# Distribution stage with some tooling
#########################################
FROM alpinelinux/docker-cli:latest AS distrib

# Repository location
ARG REPOSITORY=github.com/sigreen-nokia

# Artifact name
ARG ARTIFACT=lexx

# User
ARG USER=lexx
ARG UID=1000

# Create non-root user
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --no-create-home \
    --uid "$UID" \
    "$USER"

# Install deps
RUN apk add --no-cache bash gcompat git openssl openssh-client curl jq docker-cli-compose aha

# Install binary and entrypoint
COPY --from=builder /go/src/$REPOSITORY/$ARTIFACT/release/$ARTIFACT /usr/local/bin/$ARTIFACT
COPY docker-entrypoint.sh /

# Define entrypoint
ENTRYPOINT ["/docker-entrypoint.sh"]

VOLUME [ "/scripts" ]

EXPOSE 8080

USER $USER

#http
CMD [ "lexx" ]
#https using tls
#this tls options requires certificates
#CMD [ "lexx", "--tls" ]
#https tls using acme protocol (you must specify your domain)
#CMD [ "lexx", "--tls", "--tls-domain=hook.example.com" ]
#debugging lexx
#CMD [ "lexx", "--log-level", "debug", "--log-http-request", "--log-hook-output"  ]

